#
# _________     _____  ________    .____
# \_   ___ \   /     \ \______ \   |    |    ____   ____   ____   ___________
# /    \  \/  /  \ /  \ |    |  \  |    |   /  _ \ / ___\ / ___\_/ __ \_  __ \
# \     \____/    Y    \|    `   \ |    |__(  <_> ) /_/  > /_/  >  ___/|  | \/
# \______  /\____|__  /_______  / |_______ \____/\___  /\___  / \___  >__|
# \/         \/        \/          \/    /_____//_____/      \/
#
#
# _________                _____.__         ___________.__.__
# \_   ___ \  ____   _____/ ____\__| ____   \_   _____/|__|  |   ____
# /    \  \/ /  _ \ /    \   __\|  |/ ___\   |    __)  |  |  | _/ __ \
# \     \___(  <_> )   |  \  |  |  / /_/  >  |     \   |  |  |_\  ___/
# \______  /\____/|___|  /__|  |__\___  /   \___  /   |__|____/\___  >
# \/            \/        /_____/        \/                 \/
#

# ------------------------------------------------------------------------------------------------------------
#
#
#
# ___    ____ _____   __   ___   ____   ___
#   |   \  |    / ___/  /  ] /   \ |    \ |   \
#     |    \  |  (   \_  /  / |     ||  D  )|    \
#     |  D  | |  |\__  |/  /  |  O  ||    / |  D  |
#     |     | |  |/  \ /   \_ |     ||    \ |     |
#     |     | |  |\    \     ||     ||  .  \|     |
#     |_____||____|\___|\____| \___/ |__|\_||_____|

# Discord WebHook URL
webhook-url: 'your-webhook-url'

# Embed Settings
embed:
  title: 'Staffs Commands Logger'
  color: '#020101' # Must be in Hex

# Ignored Commands
ignored-commands:
  - "examplecommand1"